import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {ApiError,actor,database,jsonBody,limitedBody,now,rateLimit,record,sameOrigin,settings,verifyImages} from '@/lib/server';
import {profileSchema,listingSchema,postSchema} from '@/lib/validation';
import {seedListings,seedPosts,defaultProfile,type Listing,type BoardPost} from '@/lib/car-domain';
import {refreshMarket} from '@/lib/refresh';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function handle(req:Request){try{
 const url=new URL(req.url),parts=url.pathname.split('/').filter(Boolean).slice(1),route=parts[0],id=parts[1],method=req.method;
 if(route==='refresh'){if(method!=='POST')throw new ApiError(405,'허용되지 않는 요청이에요.');sameOrigin(req);const secret=settings().REFRESH_SECRET;const supplied=req.headers.get('authorization');const isService=!!secret&&secret.length>=32&&supplied===`Bearer ${secret}`;if(!isService){const u=await actor(true);if(!u?.isadmin)throw new ApiError(403,'관리자만 갱신할 수 있어요.');}return response(await refreshMarket());}
 if(route==='media'&&method==='GET'&&id){const row=await database().prepare('SELECT * FROM media WHERE id=?').bind(id).first<{ownerid:string;objectkey:string;type:string}>();if(!row)throw new ApiError(404,'사진을 찾지 못했어요.');const active=await database().prepare("SELECT r.id FROM records r,json_each(r.data,'$.images') AS image WHERE r.delat=0 AND image.value=? LIMIT 1").bind(`/api/media/${id}`).first();if(!active){const u=await actor();if(u?.id!==row.ownerid)throw new ApiError(404,'사진을 찾지 못했어요.');}const file=await env.BUCKET?.get(row.objectkey);if(!file)throw new ApiError(404,'사진을 찾지 못했어요.');return new Response(file.body,{headers:{'Content-Type':row.type,'Cache-Control':'private, max-age=120','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}
 const user=await actor(method!=='GET');const db=database();
 if(method==='GET'&&route==='state'){
  const [raw,blocks,favs,prof,counts,runs,snaps]=await Promise.all([
   db.prepare('SELECT r.*,u.alias FROM records r LEFT JOIN users u ON r.ownerid=u.id WHERE r.delat=0 ORDER BY r.updatedat DESC LIMIT 500').all(),
   user?db.prepare('SELECT targetid FROM blocks WHERE userid=? AND active=1').bind(user.id).all():Promise.resolve({results:[]}),
   user?db.prepare('SELECT listingid FROM favorites WHERE userid=? AND active=1 ORDER BY createdat').bind(user.id).all():Promise.resolve({results:[]}),
   user?db.prepare('SELECT data FROM profiles WHERE userid=?').bind(user.id).first<{data:string}>():Promise.resolve(null),
   db.prepare('SELECT postid,count(*) AS n FROM comments WHERE delat=0 GROUP BY postid').all(),
   db.prepare('SELECT * FROM refresh_runs ORDER BY startedat DESC LIMIT 1').first(),
   db.prepare('SELECT * FROM market_snapshots ORDER BY fetchedat DESC LIMIT 1').first<{data:string;source:string;sourceurl:string;observedat:string;fetchedat:string}>()
  ]);
  const blocked=new Set(blocks.results.map((x:any)=>x.targetid));const visible=raw.results.filter((r:any)=>!blocked.has(r.ownerid));
  const listings=[...visible.filter((r:any)=>r.kind==='listing').map((r:any)=>({...JSON.parse(r.data),id:r.id,ownerid:r.ownerid,createdat:r.createdat,updatedat:r.updatedat,demo:false,verified:false})),...seedListings.filter(x=>!blocked.has(x.ownerid))];
  const posts=[...visible.filter((r:any)=>r.kind==='post').map((r:any)=>({...JSON.parse(r.data),id:r.id,ownerid:r.ownerid,author:r.alias,createdat:r.createdat,updatedat:r.updatedat,demo:false})),...seedPosts.filter(x=>!blocked.has(x.ownerid))].map(p=>({...p,comments:Number((counts.results.find((x:any)=>x.postid===p.id) as any)?.n||0)}));
  return response({user,listings,posts,profile:prof?JSON.parse(prof.data):defaultProfile,favorites:favs.results.map((x:any)=>x.listingid),blocks:[...blocked],market:snaps?JSON.parse(snaps.data):[],source:snaps?{name:snaps.source,url:snaps.sourceurl,observedat:snaps.observedat,fetchedat:snaps.fetchedat}:null,refresh:runs});
 }
 if(method==='GET'&&route==='comments'){const postid=url.searchParams.get('postid')||'';const post=seedPosts.find(x=>x.id===postid)||await record(postid);if(!post)throw new ApiError(404,'글을 찾지 못했어요.');const rows=await db.prepare('SELECT c.*,u.alias AS author FROM comments c JOIN users u ON c.ownerid=u.id WHERE c.postid=? AND c.delat=0 AND NOT EXISTS (SELECT 1 FROM blocks b WHERE b.userid=? AND b.targetid=c.ownerid AND b.active=1) ORDER BY c.createdat LIMIT 300').bind(postid,user?.id||'').all();return response(rows.results);}
 if(method==='GET'&&route==='inquiries'){if(!user)throw new ApiError(401,'로그인 후 확인할 수 있어요.');const rows=await db.prepare('SELECT i.*,s.alias AS sender,r.alias AS recipient FROM inquiries i JOIN users s ON i.senderid=s.id JOIN users r ON i.recipientid=r.id WHERE i.senderid=? OR i.recipientid=? ORDER BY i.createdat DESC LIMIT 100').bind(user.id,user.id).all();return response(rows.results);}
 if(method==='GET'&&route==='reports'){if(!user?.isadmin)throw new ApiError(403,'관리자 권한이 필요해요.');return response((await db.prepare('SELECT * FROM reports ORDER BY createdat DESC LIMIT 200').all()).results);}
 if(method==='GET')throw new ApiError(404,'요청한 항목을 찾지 못했어요.');
 sameOrigin(req);if(!user)throw new ApiError(401,'로그인이 필요해요.');await rateLimit(user.id,route);
 if(route==='upload'&&method==='POST'){
  if(!env.BUCKET)throw new ApiError(503,'사진 저장소에 연결하지 못했어요.');const body=await limitedBody(req,6*1024*1024);const form=await new Request(req.url,{method:'POST',headers:{'Content-Type':req.headers.get('content-type')||''},body}).formData();const file=form.get('file');if(!(file instanceof File)||file.size===0||file.size>5*1024*1024)throw new ApiError(400,'5MB 이하의 사진을 선택해 주세요.');const data=await file.arrayBuffer(),v=new Uint8Array(data);let type='',ext='';if(v[0]===255&&v[1]===216&&v[2]===255){type='image/jpeg';ext='jpg';}else if(v[0]===137&&v[1]===80&&v[2]===78&&v[3]===71){type='image/png';ext='png';}else if(new TextDecoder().decode(v.slice(0,4))==='RIFF'&&new TextDecoder().decode(v.slice(8,12))==='WEBP'){type='image/webp';ext='webp';}else throw new ApiError(400,'JPG, PNG, WebP 사진만 업로드할 수 있어요.');const mid=crypto.randomUUID(),key=`uploads/${mid}.${ext}`;await env.BUCKET.put(key,data,{httpMetadata:{contentType:type}});await db.prepare('INSERT INTO media(id,ownerid,objectkey,type,size,createdat) VALUES(?,?,?,?,?,?)').bind(mid,user.id,key,type,file.size,now()).run();return response({url:`/api/media/${mid}`},201);
 }
 const data=await jsonBody(req);
 if(route==='profile'&&method==='PUT'){const p=profileSchema.parse(data);await db.prepare('INSERT INTO profiles(userid,data,updatedat) VALUES(?,?,?) ON CONFLICT(userid) DO UPDATE SET data=excluded.data,updatedat=excluded.updatedat').bind(user.id,JSON.stringify(p),now()).run();return response({ok:true});}
 if(route==='account'&&method==='PUT'){const alias=z.string().trim().min(2).max(30).parse(data.alias);await db.prepare('UPDATE users SET alias=? WHERE id=?').bind(alias,user.id).run();return response({ok:true});}
 if((route==='listings'||route==='posts')&&(method==='POST'||method==='PUT')){
  const kind=route==='listings'?'listing':'post';const payload=kind==='listing'?listingSchema.parse(data):postSchema.parse(data);await verifyImages(payload.images,user.id);const old=method==='PUT'&&id?await record(id):null;if(method==='PUT'&&(!old||old.ownerid!==user.id||old.kind!==kind))throw new ApiError(403,'직접 등록한 항목만 수정할 수 있어요.');const rid=old?.id||crypto.randomUUID(),time=now();const extra=kind==='listing'?{previousprice:old?((JSON.parse(old.data).price===('price' in payload?payload.price:0))?JSON.parse(old.data).previousprice:JSON.parse(old.data).price):null}:{};const json=JSON.stringify({...payload,...extra});if(old)await db.prepare('UPDATE records SET modelkey=?,category=?,price=?,status=?,data=?,updatedat=? WHERE id=? AND ownerid=? AND delat=0').bind(payload.modelkey,'category' in payload?payload.category:'','price' in payload?payload.price:0,'status' in payload?payload.status:'active',json,time,rid,user.id).run();else await db.prepare('INSERT INTO records(id,kind,ownerid,modelkey,category,price,status,data,createdat,updatedat) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(rid,kind,user.id,payload.modelkey,'category' in payload?payload.category:'','price' in payload?payload.price:0,'status' in payload?payload.status:'active',json,time,time).run();return response({id:rid},old?200:201);
 }
 if(route==='hide'&&method==='POST'){const rid=z.string().uuid().parse(data.id);const old=await record(rid);if(!old||(old.ownerid!==user.id&&!user.isadmin))throw new ApiError(403,'숨김 권한이 없어요.');await db.prepare('UPDATE records SET delat=1,updatedat=? WHERE id=?').bind(now(),rid).run();return response({ok:true});}
 if(route==='favorites'&&method==='PUT'){const value=z.object({listingid:z.string().max(100),active:z.boolean()}).parse(data);const target=seedListings.find(x=>x.id===value.listingid)||await record(value.listingid);if(!target||('kind' in target&&target.kind!=='listing'))throw new ApiError(404,'매물을 찾지 못했어요.');await db.prepare('INSERT INTO favorites(userid,listingid,active,createdat) VALUES(?,?,?,?) ON CONFLICT(userid,listingid) DO UPDATE SET active=excluded.active').bind(user.id,value.listingid,value.active?1:0,now()).run();return response({ok:true});}
 if(route==='comments'&&method==='POST'){const value=z.object({postid:z.string().max(100),body:z.string().trim().min(1).max(3000)}).parse(data);const target=seedPosts.find(x=>x.id===value.postid)||await record(value.postid);if(!target||('kind' in target&&target.kind!=='post'))throw new ApiError(404,'글을 찾지 못했어요.');await db.prepare('INSERT INTO comments(id,postid,ownerid,body,createdat) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),value.postid,user.id,value.body,now()).run();return response({ok:true},201);}
 if(route==='comments'&&method==='PATCH'){const value=z.object({id:z.string().uuid(),body:z.string().trim().min(1).max(3000).optional(),hide:z.boolean().optional()}).parse(data);const old=await db.prepare('SELECT ownerid FROM comments WHERE id=? AND delat=0').bind(value.id).first<{ownerid:string}>();if(!old||(old.ownerid!==user.id&&!user.isadmin))throw new ApiError(403,'수정 권한이 없어요.');if(value.hide)await db.prepare('UPDATE comments SET delat=1 WHERE id=?').bind(value.id).run();else if(value.body)await db.prepare('UPDATE comments SET body=? WHERE id=?').bind(value.body,value.id).run();return response({ok:true});}
 if(route==='inquiries'&&method==='POST'){const value=z.object({listingid:z.string().max(100),body:z.string().trim().min(3).max(3000)}).parse(data);const listing=await record(value.listingid);if(!listing||listing.kind!=='listing')throw new ApiError(400,'예시 매물에는 실제 문의를 보낼 수 없어요.');if(listing.status==='판매완료')throw new ApiError(400,'판매완료된 매물이에요.');if(listing.ownerid===user.id)throw new ApiError(400,'본인 매물에는 문의할 수 없어요.');const block=await db.prepare('SELECT 1 FROM blocks WHERE active=1 AND ((userid=? AND targetid=?) OR (userid=? AND targetid=?))').bind(user.id,listing.ownerid,listing.ownerid,user.id).first();if(block)throw new ApiError(403,'문의할 수 없는 사용자입니다.');await db.prepare('INSERT INTO inquiries(id,listingid,senderid,recipientid,body,createdat) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),listing.id,user.id,listing.ownerid,value.body,now()).run();return response({ok:true},201);}
 if(route==='blocks'&&method==='PUT'){const value=z.object({targetid:z.string().min(1).max(150),active:z.boolean()}).parse(data);if(value.targetid===user.id)throw new ApiError(400,'본인은 차단할 수 없어요.');await db.prepare('INSERT INTO blocks(userid,targetid,active) VALUES(?,?,?) ON CONFLICT(userid,targetid) DO UPDATE SET active=excluded.active').bind(user.id,value.targetid,value.active?1:0).run();return response({ok:true});}
 if(route==='reports'&&method==='POST'){const value=z.object({targettype:z.enum(['listing','post','comment']),targetid:z.string().min(1).max(100),reason:z.string().trim().min(3).max(1000)}).parse(data);await db.prepare('INSERT INTO reports(id,reporterid,targettype,targetid,reason,status,createdat) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user.id,value.targettype,value.targetid,value.reason,'접수',now()).run();return response({ok:true},201);}
 if(route==='reports'&&method==='PATCH'){if(!user.isadmin)throw new ApiError(403,'관리자 권한이 필요해요.');const value=z.object({id:z.string().uuid(),status:z.enum(['접수','확인','처리완료'])}).parse(data);await db.prepare('UPDATE reports SET status=? WHERE id=?').bind(value.status,value.id).run();return response({ok:true});}
 throw new ApiError(404,'요청한 기능을 찾지 못했어요.');
 }catch(e){if(e instanceof z.ZodError)return response({error:'입력한 항목의 범위와 형식을 확인해 주세요.',fields:e.issues.map(i=>({field:i.path.join('.'),message:i.message}))},400);if(e instanceof ApiError)return response({error:e.message},e.status);console.error('API error',e instanceof Error?e.message:'unknown');return response({error:'처리하지 못했어요. 입력 내용은 유지되니 잠시 후 다시 시도해 주세요.'},503);}}
export const GET=handle;export const POST=handle;export const PUT=handle;export const PATCH=handle;
