export type Profile={budget:number;monthly:number;includeinitial:boolean;payment:'cash'|'loan';downpayment:number;months:number;apr:number;age:number;drivingyears:number;insuranceyears:number;annualkm:number;purpose:'commute'|'travel'|'family';passengers:number;parking:'normal'|'tight';charging:boolean;parkingfee:number;toll:number;fuelprice:number;insurancequote:number|null;weights:{cost:number;purpose:number;space:number}};
export const defaultProfile:Profile={budget:1500,monthly:45,includeinitial:false,payment:'cash',downpayment:500,months:36,apr:6,age:29,drivingyears:3,insuranceyears:1,annualkm:12000,purpose:'commute',passengers:2,parking:'normal',charging:false,parkingfee:5,toll:2,fuelprice:1700,insurancequote:null,weights:{cost:50,purpose:30,space:20}};
export type CarModel={id:string;name:string;make:string;generation:string;fuel:string;body:string;seats:number;efficiency:[number,number];insurance:[number,number];tax:number;reserve:[number,number];initial:number;purpose:{commute:number;travel:number;family:number};space:number;parking:number;pros:string[];cons:string[];checks:string[]};
export const models:CarModel[]=[
{id:'niro',name:'니로 하이브리드',make:'기아',generation:'DE',fuel:'하이브리드',body:'SUV',seats:5,efficiency:[15.5,21.5],insurance:[8,12],tax:1.5,reserve:[6,10],initial:95,purpose:{commute:95,travel:88,family:88},space:85,parking:75,pros:['예시 연비 기준 연료비 부담이 낮아요','출퇴근과 가끔 여행을 함께 고려하기 좋아요'],cons:['구입 전 정비 기록과 예비비를 확인하세요'],checks:['저속 변속감과 냉간 시동','하이브리드 계통 점검 기록','리콜 대상 여부는 차대번호로 별도 확인']},
{id:'avante',name:'아반떼 AD',make:'현대',generation:'AD',fuel:'가솔린',body:'세단',seats:5,efficiency:[11.3,15.5],insurance:[7,11],tax:1.5,reserve:[5,8],initial:85,purpose:{commute:88,travel:90,family:78},space:80,parking:78,pros:['예시 구매비와 공간의 균형이 좋아요','장거리 비중이 늘면 목적 적합도가 높아져요'],cons:['예시 조건에서는 하이브리드보다 유류비가 커요'],checks:['엔진 냉간 시동 상태','정비·소모품 교환 이력','사고 설명과 성능점검 자료 대조']},
{id:'morning',name:'올 뉴 모닝',make:'기아',generation:'JA',fuel:'가솔린',body:'경차',seats:5,efficiency:[13,18.5],insurance:[6,10],tax:.7,reserve:[4,7],initial:45,purpose:{commute:82,travel:55,family:52},space:50,parking:98,pros:['예시 구매비·월 지출에 여유가 생겨요','좁은 주차 환경을 중요하게 보면 유리해요'],cons:['장거리·넓은 공간을 우선하면 적합도가 낮아져요'],checks:['하체 소음과 타이어 상태','브레이크·소모품 교환 기록','실제 승차와 적재 공간 확인']}
];
export function modelOf(key:string){return models.find(m=>m.id===key)}
export type Listing={id:string;ownerid:string;modelkey:string;title:string;year:number;firstregistered:string;trim:string;mileage:number;price:number;previousprice:number|null;region:string;sellertype:'개인'|'사업자';status:'판매중'|'예약중'|'판매완료';accident:'미입력'|'없음'|'있음';repair:string;maintenance:string;options:string[];description:string;images:string[];createdat:string;updatedat:string;demo:boolean;verified:boolean;transmission:string;make?:string;modelname?:string;generation?:string;fuel?:string};
export const seedListings:Listing[]=[
{id:'demo-niro',ownerid:'demo-seller-1',modelkey:'niro',title:'출퇴근용으로 관리한 니로 프레스티지',year:2017,firstregistered:'2017-06',trim:'1.6 HEV 프레스티지',mileage:110000,price:1250,previousprice:1280,region:'서울 송파',sellertype:'개인',status:'판매중',accident:'없음',repair:'판매자 입력 예시. 증빙 미확인.',maintenance:'엔진오일 교체 이력 예시. 증빙 미확인.',options:['열선시트','후방카메라','스마트키'],description:'차량을 살펴보는 흐름을 위한 가상 매물입니다. 실제 판매 차량이 아닙니다.',images:[],createdat:'2026-09-28T09:00:00.000Z',updatedat:'2026-09-30T00:00:00.000Z',demo:true,verified:false,transmission:'자동'},
{id:'demo-avante',ownerid:'demo-seller-2',modelkey:'avante',title:'첫 차로 고민하기 좋은 아반떼 AD',year:2018,firstregistered:'2018-04',trim:'1.6 GDi 스마트',mileage:90000,price:1050,previousprice:null,region:'경기 수원',sellertype:'개인',status:'판매중',accident:'미입력',repair:'',maintenance:'',options:['후방카메라','크루즈컨트롤'],description:'비교 기능을 확인할 수 있는 가상 매물입니다.',images:[],createdat:'2026-09-29T09:00:00.000Z',updatedat:'2026-09-29T09:00:00.000Z',demo:true,verified:false,transmission:'자동'},
{id:'demo-morning',ownerid:'demo-seller-3',modelkey:'morning',title:'도심 이동에 편한 올 뉴 모닝',year:2019,firstregistered:'2019-03',trim:'JA 1.0 럭셔리',mileage:65000,price:800,previousprice:null,region:'서울 강서',sellertype:'사업자',status:'예약중',accident:'없음',repair:'',maintenance:'교체 내역 확인 전',options:['열선시트','후방센서'],description:'차값과 유지비의 차이를 보여주는 가상 매물입니다.',images:[],createdat:'2026-09-27T09:00:00.000Z',updatedat:'2026-09-30T00:00:00.000Z',demo:true,verified:false,transmission:'자동'}];
export type BoardPost={id:string;ownerid:string;author:string;category:string;title:string;body:string;modelkey:string;images:string[];createdat:string;updatedat:string;comments:number;demo:boolean};
export const categories=['전체','자유게시판','구매상담','차량 추천','차종별 후기','정비·유지비'];
export const seedPosts:BoardPost[]=[
{id:'demo-post-1',ownerid:'demo-author-1',author:'차근가이드',category:'구매상담',title:'차값만 준비했다가 놓치기 쉬운 네 가지 비용',body:'구매예산과 월 지출 한도를 따로 생각해 보세요.\n\n차값 외에 취득·등록에 드는 비용, 본인의 보험 견적, 첫 정비에 필요한 금액을 확인하면 선택이 쉬워집니다.\n\n구매 후에는 유류비와 주차비, 정비 대비금까지 월평균으로 계산해 보세요.\n\n이 글은 게시판 구성을 위한 예시 콘텐츠입니다.',modelkey:'',images:[],createdat:'2026-09-29T01:00:00.000Z',updatedat:'2026-09-29T01:00:00.000Z',comments:0,demo:true},
{id:'demo-post-2',ownerid:'demo-author-2',author:'예비차주',category:'차량 추천',title:'니로와 아반떼, 출퇴근용으로 어떤 항목부터 비교할까요?',body:'예산 1,500만원, 월 한도 45만원으로 처음 차를 고르는 상황을 가정한 질문입니다.\n유지비와 주차 편의성을 중요하게 보고 있어요.',modelkey:'niro',images:[],createdat:'2026-09-30T01:00:00.000Z',updatedat:'2026-09-30T01:00:00.000Z',comments:0,demo:true},
{id:'demo-post-3',ownerid:'demo-author-3',author:'차곡차곡',category:'정비·유지비',title:'정비비는 매달 실제로 나가는 돈인가요?',body:'정비 대비금은 매달 확정되는 청구액이 아니라 수리·소모품 교체에 대비해 모아두는 예상액입니다. 실제 지출은 차량 상태에 따라 달라집니다.\n\n이 글은 예시 콘텐츠입니다.',modelkey:'',images:[],createdat:'2026-09-28T01:00:00.000Z',updatedat:'2026-09-28T01:00:00.000Z',comments:0,demo:true}];
export const round=(n:number)=>Math.round(n*10)/10;
export const format=(n:number)=>Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:1}):'미입력';
export function installment(principal:number,apr:number,months:number){if(!Number.isFinite(principal)||!Number.isFinite(apr)||!Number.isFinite(months)||months<1||apr<0)return 0;if(principal<=0)return 0;const r=apr/1200;return r===0?principal/months:principal*r/(1-(1+r)**-months)}
export function evaluate(listing:Listing,p:Profile){const m=modelOf(listing.modelkey);if(!m)return null;const inputs=[p.budget,p.monthly,p.annualkm,p.parkingfee,p.toll,p.fuelprice,p.downpayment,p.apr,p.months];if(inputs.some(x=>!Number.isFinite(x)||x<0)||p.monthly<5||p.budget<100||p.months<1||p.fuelprice<500||p.insurancequote!==null&&(!Number.isFinite(p.insurancequote)||p.insurancequote<0))return null;
 const insurer=p.insurancequote!==null?[p.insurancequote/12,p.insurancequote/12]:m.insurance;
 const insurance:[number,number]=[round(insurer[0]),round(insurer[1])];
 const fuel:[number,number]=[round(p.annualkm/12/m.efficiency[1]*p.fuelprice/10000),round(p.annualkm/12/m.efficiency[0]*p.fuelprice/10000)];
 const loan=round(p.payment==='loan'?installment(Math.max(0,listing.price-p.downpayment),p.apr,p.months):0);
 const low=round(insurance[0]+fuel[0]+m.tax+m.reserve[0]+p.parkingfee+p.toll+loan),high=round(insurance[1]+fuel[1]+m.tax+m.reserve[1]+p.parkingfee+p.toll+loan);
 const initial=round((p.payment==='loan'?Math.min(listing.price,p.downpayment):listing.price)+m.initial);
 const acquisition=listing.price+(p.includeinitial?m.initial:0);
 const scores={cost:Math.max(0,Math.min(100,100-high/Math.max(1,p.monthly)*25)),purpose:m.purpose[p.purpose],space:p.parking==='tight'?m.parking:m.space};
 if(p.drivingyears<1)scores.space=(scores.space+m.parking)/2;
 if(p.passengers>=4&&m.body==='경차')scores.space=Math.min(scores.space,40);
 const sum=p.weights.cost+p.weights.purpose+p.weights.space;
 const score=Math.round((scores.cost*p.weights.cost+scores.purpose*p.weights.purpose+scores.space*p.weights.space)/(sum||1));
 const blockers:string[]=[];if(acquisition>p.budget)blockers.push('구매예산 초과');if(high>p.monthly)blockers.push(low>p.monthly?'월 지출 한도 초과':'월 지출 초과 가능');if(p.passengers>m.seats)blockers.push('탑승 인원 초과');if(listing.status==='판매완료')blockers.push('판매완료');
 const reasons=[m.pros[0],`예상 월 ${format(low)}–${format(high)}만원으로 ${high<=p.monthly?`상단 기준 ${format(p.monthly-high)}만원 여유가 있어요`:`상단 기준 ${format(high-p.monthly)}만원 초과할 수 있어요`}`,p.parking==='tight'?'좁은 주차 환경에 맞춰 주차 편의성을 반영했어요':`사용 목적 ‘${({commute:'출퇴근',travel:'여행·장거리',family:'가족용'})[p.purpose]}’를 반영했어요`];
 const uncertainty=p.insurancequote===null?`${p.age}세 · 운전 ${p.drivingyears}년 · 보험가입 ${p.insuranceyears}년 조건의 실제 보험 견적이 필요해요. 현재 보험료 범위는 가상 기준값으로, 나이·경력으로 실제 견적을 대체하지 않았어요.`:'직접 입력한 연 보험료를 12개월로 나눴어요. 다른 차량에도 동일 견적이 적용되는지는 확인해 주세요.';
 return {model:m,insurance,fuel,loan,low,high,initial,acquisition,scores,score,blockers,reasons,uncertainty,eligible:blockers.length===0,demo:true};
}
export type MarketRow={id:string;modelkey:string;trim:string;year:number;mileage:number;price:number;accident:string;observedat:string;source:string;sourceurl:string};
export function marketSummary(car:Listing,rows:MarketRow[],now=Date.now()){
 if(!modelOf(car.modelkey))return {available:false as const,n:0,reason:'차종·세대 식별 자료가 연결되어야 비교할 수 있어요.'};
 const seen=new Set<string>();const valid=rows.filter(r=>{if(seen.has(r.id))return false;seen.add(r.id);return r.modelkey===car.modelkey&&r.trim.trim()===car.trim.trim()&&Math.abs(r.year-car.year)<=1&&Math.abs(r.mileage-car.mileage)<=20000&&r.accident===car.accident&&car.accident!=='미입력'&&r.price>0&&Number.isFinite(Date.parse(r.observedat))&&now-Date.parse(r.observedat)<30*86400000&&Date.parse(r.observedat)<=now}).sort((a,b)=>a.price-b.price);
 if(valid.length<10)return {available:false as const,n:valid.length,reason:'동일 조건의 최근 등록 매물 10건 이상이 필요해요.'};
 const quant=(a:number[],t:number)=>{const pos=(a.length-1)*t,lo=Math.floor(pos),hi=Math.ceil(pos);return a[lo]+(a[hi]-a[lo])*(pos-lo)};
 const prices=valid.map(r=>r.price),q1=quant(prices,.25),q3=quant(prices,.75),iqr=q3-q1;const trimmed=valid.filter(r=>r.price>=q1-1.5*iqr&&r.price<=q3+1.5*iqr);
 if(trimmed.length<10)return {available:false as const,n:trimmed.length,reason:'이상값 제외 후 비교 자료가 부족해요.'};const vals=trimmed.map(r=>r.price);
 return {available:true as const,n:vals.length,mean:round(vals.reduce((a,b)=>a+b,0)/vals.length),median:round(quant(vals,.5)),low:round(quant(vals,.25)),high:round(quant(vals,.75)),observedat:trimmed.map(r=>r.observedat).sort()[0],sources:[...new Set(trimmed.map(r=>r.source))],excluded:valid.length-trimmed.length};
}
