import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const settings=()=>env as Cloudflare.Env & {ADMIN_USER_IDS?:string;MARKET_DATA_URL?:string;MARKET_DATA_TOKEN?:string;SOURCE_LICENSE_CONFIRMED?:string;REFRESH_SECRET?:string};
export function database(){if(!env.DB)throw new ApiError(503,'저장소에 연결하지 못했어요. 잠시 후 다시 시도해 주세요.');return env.DB}
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export const now=()=>new Date().toISOString();
export async function actor(required=false){const auth=await getChatGPTUser();if(!auth){if(required)throw new ApiError(401,'로그인 후 이용할 수 있어요.');return null;}const db=database();const fallback='차근회원'+auth.userId.slice(-5);await db.prepare('INSERT OR IGNORE INTO users(id,alias,createdat) VALUES(?,?,?)').bind(auth.userId,fallback,now()).run();const row=await db.prepare('SELECT alias FROM users WHERE id=?').bind(auth.userId).first<{alias:string}>();return {id:auth.userId,alias:row?.alias||fallback,isadmin:(settings().ADMIN_USER_IDS||'').split(',').map(x=>x.trim()).includes(auth.userId)}}
export async function limitedBody(req:Request,max:number){const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let length=0;while(true){const r=await reader.read();if(r.done)break;length+=r.value.length;if(length>max){await reader.cancel();throw new ApiError(413,'파일 또는 입력 내용이 너무 커요.');}chunks.push(r.value)}const out=new Uint8Array(length);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.length}return out}
export async function jsonBody(req:Request){try{return JSON.parse(new TextDecoder().decode(await limitedBody(req,100000)))}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(400,'입력 형식을 확인해 주세요.')}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if((origin&&origin!==new URL(req.url).origin)||req.headers.get('sec-fetch-site')==='cross-site')throw new ApiError(403,'이 페이지에서 다시 요청해 주세요.');}
export async function rateLimit(userid:string,action:string){const db=database();const since=new Date(Date.now()-60000).toISOString();const count=await db.prepare('SELECT count(*) AS n FROM events WHERE userid=? AND createdat>?').bind(userid,since).first<{n:number}>();if((count?.n||0)>=40)throw new ApiError(429,'요청이 많아요. 잠시 후 다시 시도해 주세요.');await db.prepare('INSERT INTO events(id,userid,action,createdat) VALUES(?,?,?,?)').bind(crypto.randomUUID(),userid,action,now()).run()}
export async function verifyImages(paths:string[],ownerid:string){for(const path of paths){const row=await database().prepare('SELECT ownerid FROM media WHERE id=?').bind(path.split('/').pop()).first<{ownerid:string}>();if(!row||row.ownerid!==ownerid)throw new ApiError(403,'직접 업로드한 사진만 첨부할 수 있어요.');}}
export async function record(id:string){return database().prepare('SELECT * FROM records WHERE id=? AND delat=0').bind(id).first<{id:string;ownerid:string;kind:string;data:string;status:string}>()}
